# Generated by Django 5.2.7 on 2025-11-25 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pedidos", "0001_initial"),
        ("Productos", "0006_alter_producto_vendedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidodetalle",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedidos_detalle",
                to="Productos.producto",
            ),
        ),
    ]
