# Generated by Django 5.2.7 on 2025-11-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Productos", "0002_categoria_marca_producto_activo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marca",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="marcas/"),
        ),
    ]
