# Generated by Django 5.2.7 on 2025-11-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Productos", "0003_marca_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marca",
            name="imagen",
        ),
    ]
