# Generated by Django 5.2.7 on 2025-11-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Productos", "0006_alter_producto_vendedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="porcentaje_ganancia",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_costo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
