# Generated by Django 5.2.7 on 2026-01-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Productos",
            "0007_producto_porcentaje_ganancia_producto_precio_costo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="porcentaje_descuento",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_final",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
