# Generated by Django 5.2.7 on 2025-11-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("CLIENTE", "Cliente"),
                    ("VENDEDOR", "Vendedor"),
                ],
                default="CLIENTE",
                max_length=15,
                verbose_name="Rol",
            ),
        ),
    ]
